---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 762118532968525824-Xsl8pVeRbH7kIHRZ5S29hlgO4OgGXvR
:access_token_secret: r9qUcmEVV5M9u5IArtM2Ox59t9hbjnwLvBFJWVDbIsgDd
